version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- nuget restore
build:
  project: ACSE.sln
  verbosity: minimal
after_build:
- cmd: 7z a -tzip "ACSE.WinForms/bin/Release/ACSE.zip" "ACSE.WinForms/bin/Release/*"
artifacts:
- path: ACSE.WinForms/bin/Release/ACSE.zip
  name: build
